sonar.projectKey=ticketbox-checker
sonar.organization=jakeconal
sonar.projectName=TicketBox Checker
sonar.sources=src,App.tsx,index.js
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.sourceEncoding=UTF-8
