sonar.projectKey=ticketbox-web
sonar.organization=jakeconal
sonar.projectName=TicketBox Web
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8
