apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketbox-config
  labels:
    app.kubernetes.io/part-of: ticketbox-app
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
