export const ui = {
  page: "mx-auto min-h-dvh w-full max-w-7xl px-4 py-4 sm:px-6 sm:py-6 lg:px-8",
  authPage: "grid min-h-dvh place-items-center px-4 py-8 sm:px-6",
  adminPage: "min-h-dvh px-4 py-4 sm:px-6 sm:py-6 lg:px-8",
  nav: "mb-10 flex flex-wrap items-center justify-between gap-3 border-y border-neutral-950 py-3",
  brand: "inline-flex min-h-11 items-center text-lg font-black text-neutral-950 no-underline",
  navActions: "flex flex-wrap items-center gap-2",
  primaryButton: "inline-flex min-h-11 items-center justify-center border border-neutral-950 bg-neutral-950 px-4 py-2 text-sm font-semibold text-white no-underline transition-colors hover:bg-neutral-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-950 disabled:cursor-not-allowed disabled:opacity-45",
  secondaryButton: "inline-flex min-h-11 items-center justify-center border border-neutral-950 bg-white px-4 py-2 text-sm font-semibold text-neutral-950 no-underline transition-colors hover:bg-neutral-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-950 disabled:cursor-not-allowed disabled:opacity-45",
  ghostButton: "inline-flex min-h-11 items-center justify-center border border-transparent bg-transparent px-3 py-2 text-sm font-semibold text-neutral-700 no-underline transition-colors hover:border-neutral-300 hover:text-neutral-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-950 disabled:cursor-not-allowed disabled:opacity-45",
  dangerButton: "inline-flex min-h-11 items-center justify-center border border-red-700 bg-white px-4 py-2 text-sm font-semibold text-red-700 transition-colors hover:bg-red-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-700 disabled:cursor-not-allowed disabled:opacity-45",
  compactButton: "min-h-10 px-3 py-1.5 text-xs",
  muted: "text-sm leading-6 text-neutral-600",
  eyebrow: "text-xs font-semibold uppercase tracking-[0.14em] text-neutral-600",
  panel: "border border-neutral-950 bg-white p-5 sm:p-6",
  form: "grid gap-4 text-sm font-medium text-neutral-950 [&_input]:mt-2 [&_input]:min-h-11 [&_input]:w-full [&_input]:border [&_input]:border-neutral-500 [&_input]:bg-white [&_input]:px-3 [&_input]:py-2 [&_input]:text-base [&_input]:font-normal [&_input]:text-neutral-950 [&_input]:outline-none [&_input]:transition-colors [&_input]:focus:border-neutral-950 [&_input]:focus-visible:outline-2 [&_input]:focus-visible:outline-offset-2 [&_input]:focus-visible:outline-neutral-950 [&_textarea]:mt-2 [&_textarea]:min-h-28 [&_textarea]:w-full [&_textarea]:border [&_textarea]:border-neutral-500 [&_textarea]:bg-white [&_textarea]:px-3 [&_textarea]:py-2 [&_textarea]:text-base [&_textarea]:font-normal [&_textarea]:text-neutral-950 [&_textarea]:outline-none [&_textarea]:transition-colors [&_textarea]:focus:border-neutral-950 [&_textarea]:focus-visible:outline-2 [&_textarea]:focus-visible:outline-offset-2 [&_textarea]:focus-visible:outline-neutral-950",
  alertError: "border border-red-700 bg-red-50 px-4 py-3 text-sm font-medium text-red-800",
  alertSuccess: "border border-neutral-950 bg-neutral-950 px-4 py-3 text-sm font-medium text-white",
  statusBadge: "inline-flex border border-neutral-500 px-2 py-1 text-xs font-semibold uppercase tracking-[0.08em] text-neutral-700",
  tableWrap: "overflow-x-auto border border-neutral-300",
  table: "w-full min-w-[38rem] border-collapse text-left text-sm [&_th]:border-b [&_th]:border-neutral-950 [&_th]:bg-neutral-100 [&_th]:px-3 [&_th]:py-3 [&_th]:font-semibold [&_td]:border-b [&_td]:border-neutral-200 [&_td]:px-3 [&_td]:py-3 [&_td]:align-top",
  rowButton: "grid w-full gap-1 text-left text-sm text-neutral-950 transition-colors hover:text-neutral-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-950",
  sectionHeading: "flex flex-wrap items-end justify-between gap-4",
  actionRow: "flex flex-wrap gap-2",
  emptyState: "border border-dashed border-neutral-400 p-6 text-sm leading-6 text-neutral-600",
  metric: "border border-neutral-300 p-4 [&_span]:block [&_span]:text-xs [&_span]:font-semibold [&_span]:uppercase [&_span]:tracking-[0.12em] [&_span]:text-neutral-600 [&_strong]:mt-3 [&_strong]:block [&_strong]:text-2xl [&_strong]:font-bold [&_strong]:text-neutral-950"
} as const;
