import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f3f4f6', // beautiful light grey matching ticketbox-web
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: Platform.OS === 'web' ? 500 : '100%',
    alignSelf: 'center',
    padding: 20,
    borderWidth: Platform.OS === 'web' ? 3 : 0,
    borderColor: '#0a0a0a',
    // shadow only on web
    shadowColor: '#0a0a0a',
    shadowOffset: Platform.OS === 'web' ? { width: 8, height: 8 } : { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#0a0a0a',
    marginBottom: 16,
  },
  title: {
    color: '#0a0a0a',
    fontSize: 20,
    fontWeight: '900', // high-contrast black heading
    letterSpacing: 1,
  },
  logoutButton: {
    backgroundColor: '#ffffff',
    borderColor: '#0a0a0a',
    borderWidth: 2,
    borderRadius: 0,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  logoutButtonText: {
    color: '#0a0a0a',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  statusBanner: {
    borderWidth: 2,
    borderColor: '#0a0a0a',
    backgroundColor: '#fef08a', // normal yellow info
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 16,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  statusBannerError: {
    backgroundColor: '#fca5a5', // red-300
  },
  statusBannerSuccess: {
    backgroundColor: '#0a0a0a', // solid black
  },
  statusText: {
    color: '#0a0a0a',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  statusTextSuccess: {
    color: '#ffffff',
  },
  cardPanel: {
    borderColor: '#0a0a0a',
    borderWidth: 2,
    backgroundColor: '#ffffff',
    padding: 16,
    marginBottom: 16,
    gap: 12,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: '800',
    color: '#737373',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  panelTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0a0a0a',
    marginTop: -4,
  },
  mutedText: {
    fontSize: 13,
    color: '#737373',
    lineHeight: 18,
  },
  form: {
    gap: 14,
    marginTop: 8,
  },
  formGroup: {
    gap: 6,
  },
  label: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0a0a0a',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#737373',
    borderWidth: 2,
    borderRadius: 0,
    color: '#0a0a0a',
    minHeight: 44,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0a0a0a',
    borderColor: '#0a0a0a',
    borderWidth: 2,
    borderRadius: 0,
    paddingVertical: 12,
    paddingHorizontal: 16,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    textTransform: 'uppercase',
    fontSize: 12,
    letterSpacing: 1,
  },
  secondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#0a0a0a',
    borderWidth: 2,
    borderRadius: 0,
    paddingVertical: 12,
    paddingHorizontal: 16,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  secondaryButtonText: {
    color: '#0a0a0a',
    fontWeight: '800',
    textTransform: 'uppercase',
    fontSize: 12,
    letterSpacing: 1,
    lineHeight: 16,
    textAlign: 'center',
  },
  scanActionButton: {
    height: 58,
    paddingHorizontal: 10,
  },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  flex: {
    flex: 1,
  },
  tabs: {
    flexDirection: 'row',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#0a0a0a',
    backgroundColor: '#0a0a0a',
    gap: 2,
  },
  tab: {
    backgroundColor: '#ffffff',
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTab: {
    backgroundColor: '#0a0a0a',
  },
  tabText: {
    color: '#0a0a0a',
    fontWeight: '800',
    textTransform: 'uppercase',
    fontSize: 12,
    letterSpacing: 1,
  },
  activeTabText: {
    color: '#ffffff',
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  badge: {
    borderWidth: 1.5,
    borderColor: '#0a0a0a',
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 0,
  },
  badgeText: {
    color: '#0a0a0a',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  scanner: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  scannerFrame: {
    width: '100%',
    aspectRatio: 1.33,
    borderWidth: 2,
    borderColor: '#0a0a0a',
    overflow: 'hidden',
    marginBottom: 12,
    backgroundColor: '#0a0a0a',
    position: 'relative',
  },
  scanFlash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffffff',
  },
  scanCaptureOverlay: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: '50%',
    marginTop: -54,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#dcfce7',
    borderColor: '#0a0a0a',
    borderWidth: 2,
    paddingHorizontal: 14,
    paddingVertical: 14,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  scanCaptureOverlaySuccess: {
    backgroundColor: '#dcfce7',
  },
  scanCaptureOverlayError: {
    backgroundColor: '#fee2e2',
  },
  scanCaptureMark: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#0a0a0a',
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  scanCaptureMarkError: {
    backgroundColor: '#dc2626',
  },
  scanCaptureMarkText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  scanCaptureTitle: {
    color: '#0a0a0a',
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 1,
  },
  scanCaptureSubtitle: {
    color: '#14532d',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginTop: 2,
  },
  scanCaptureSubtitleError: {
    color: '#7f1d1d',
  },
  scanInlineNotice: {
    borderColor: '#0a0a0a',
    borderWidth: 2,
    backgroundColor: '#dcfce7',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  scanInlineNoticeError: {
    backgroundColor: '#fee2e2',
  },
  scanInlineNoticeText: {
    color: '#0a0a0a',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  listItem: {
    backgroundColor: '#ffffff',
    borderColor: '#0a0a0a',
    borderWidth: 2,
    padding: 14,
    marginBottom: 12,
    gap: 8,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  listHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  listTitle: {
    color: '#0a0a0a',
    fontWeight: '900',
    fontSize: 14,
    flex: 1,
  },
  listMeta: {
    color: '#737373',
    fontSize: 12,
  },
  syncBadge: {
    borderWidth: 1.5,
    borderColor: '#0a0a0a',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 0,
  },
  syncBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  syncBadgePending: {
    backgroundColor: '#fef08a',
  },
  syncBadgeSynced: {
    backgroundColor: '#ffffff',
  },
  syncBadgeConflict: {
    backgroundColor: '#fca5a5',
  },
  smallButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#0a0a0a',
    borderColor: '#0a0a0a',
    borderWidth: 2,
    borderRadius: 0,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: '#0a0a0a',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  disabledButton: {
    backgroundColor: '#e5e5e5',
    borderColor: '#a3a3a3',
    shadowOpacity: 0,
  },
  smallButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  disabledButtonText: {
    color: '#a3a3a3',
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    fontWeight: '600',
  },
  panel: {
    gap: 12,
    flex: 1,
  }
});
export default styles;
